services:
  proxytunnel-go:
    image: fabiop85/proxytunnel:go
    container_name: proxytunnel-go
    restart: always
    ports:
      - "6000:6000"
    network_mode: "bridge"
    command: >
      proxy -listen 6000 -proxy sub.mydomain.tld:443 -remote level.sub.mydomain.tld:5900 -user admin -pass abc
