name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: Build binaries
        run: |
          mkdir dist
          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o dist/proxy-linux-amd64
          CGO_ENABLED=0 GOOS=linux GOARCH=arm go build -o dist/proxy-linux-arm
          CGO_ENABLED=0 GOOS=linux GOARCH=arm64 go build -o dist/proxy-linux-arm64
          CGO_ENABLED=0 GOOS=windows GOARCH=amd64 go build -o dist/proxy-windows-amd64.exe
          CGO_ENABLED=0 GOOS=windows GOARCH=arm64 go build -o dist/proxy-windows-arm64.exe
          CGO_ENABLED=0 GOOS=darwin GOARCH=amd64 go build -o dist/proxy-darwin-amd64
          CGO_ENABLED=0 GOOS=darwin GOARCH=arm64 go build -o dist/proxy-darwin-arm64

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          files: dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
